### ISSUE TITLE
Will different image width and height in training set cause errors? 

### ISSUE THREAD

**Issue by wang5566** [duxingren14/DualGAN#14]
My training set images'width and height is different, (e.g. width is 80 and height is 200). what the parameter of imgsize should I choose? 
and my training set A images' channel is 3 while B images' channel is 1, can I use "--A_channels 3 --B_channels 1 " to run the code?

**Comment by duxingren14** [comment]
The codes currently only supports images of width==height.

For the latter case,  "--A_channels 3 --B_channels 1 " is just what you
need.

**Comment by wang5566** [comment]
Thank you for your reply. I resize my training set to the same size but when run the code, I got the error message "ValueError: Dimension 1 in both shapes must be equal, but are 0 and 1 for 'concat' (op: 'ConcatV2') with input shapes: [1,0,0,512], [1,1,1,512], [] and with computed input tensors: input[2] = <3>." I don't know what's wrong with my operations? Can you give me some advice?

**Comment by duxingren14** [comment]
The size must be 128, 256, 512, 2^n...

**Comment by wang5566** [comment]
Thank you so much. I got everything done.

**Comment by wang5566** [comment]
when I set --A_channels 3 --B_channels 1, I got message "Cannot feed value of shape (1, 256, 256, 3) for Tensor u'real_B:0', which has shape '(1, 256, 256, 1)'",so what can I do?

**Comment by o0t1ng0o** [comment]
@wang5566  
I also met the problem.

But i check the images, they are all 256*256*3.
Could u please help us? @duxingren14 

Traceback (most recent call last):
  File "main.py", line 63, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 58, in main
    model.train(args)
  File "/home/valentina/DualGAN-master/model.py", line 159, in train
    self.run_optim(imgA_batch, imgB_batch, step, start_time)
  File "/home/valentina/DualGAN-master/model.py", line 178, in run_optim
    feed_dict = {self.real_A: batch_A_imgs, self.real_B: batch_B_imgs})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 975, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 256, 256, 1) for Tensor u'real_B:0', which has shape '(1, 256, 256, 3)'

**Comment by allen-ash** [comment]
@o0t1ng0o Please check again images in you data set B to see whether it's channels equals to 1.

**Comment by xiaoshidai** [comment]
Hello, I want to know if the test sample can be different from the training sample size? If so, what should I do?

**Comment by duxingren14** [comment]
Sorry, unequal width and height is not supported yet. I will try add this
feature in future version.
